# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    yaskawa_mh180_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    yaskawa_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

yaskawa_mh180_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity